name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'   # ✔ Compatible y estable

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.30.0
  firebase_messaging: ^14.7.10
  cupertino_icons: ^1.0.8   # ✔ Va aquí
  flutter_local_notifications: ^19.5.0

dependency_overrides:
  firebase_messaging_web: 3.5.0   # ✔ compatible con Flutter Web

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
